.\"
.\" Automated Testing Framework (atf)
.\"
.\" Copyright (c) 2008 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND
.\" CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
.\" INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\" GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
.\" IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\" OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
.\" IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd May 4, 2008
.Dt ATF-C-OBJECT 3
.Os
.Sh NAME
.Nm atf_disable_exit_checks ,
.Nm atf_init_objects ,
.Nm atf_object_copy ,
.Nm atf_object_fini ,
.Nm atf_object_init ,
.Nm atf_object_t
.Nd base representation for abstract objects
.Sh SYNOPSIS
.In atf-c/object.h
.\"
.Ft void
.Fn atf_object_init "atf_object_t *"
.Ft void
.Fn atf_object_copy "atf_object_t *" "const atf_object_t *"
.Ft void
.Fn atf_object_fini "atf_object_t *"
.\"
.Ft void
.Fn atf_init_objects "void"
.Ft void
.Fn atf_disable_exit_checks "void"
.\"
.Sh DESCRIPTION
.\"
The
.Nm object
module from
.Xr atf-c 3
provides the
.Nm atf_object_t
base type and complementary free functions to manage the object system
implemented by the library.
.\"
.Ss The atf_object_t type: overview
.\"
The
.Nm atf_object_t
type provides an opaque data structure that helps in the modelling of an
object-oriented programming model using the C language.
This type is meant to be used as a base type from which any other type
inherits, and all the other types provided by
.Xr atf-c 3
extend
.Nm atf_object_t .
.Pp
At the moment,
.Nm atf_object_t
only provides consistency checks for the manual management of dynamic
resources, a valuable thing due to the impossibility of applying the RAII
design patter in C.
The usage of this type also provides consistency between all data types in
.Xr atf-c 3 .
.Pp
The typical usage of
.Nm atf_object_t
to define a new type
.Ft T
is:
.Bd -literal -offset indent
struct T {
    atf_object_t m_object;

    ... other data members of T ...
};
typedef struct T T_t;
.Ed
.\"
.Ss The atf_object_t type: methods
.\"
.Bl -ohang
.It Ft void Fn atf_object_init "atf_object_t *ob"
Initializes the object pointed to by
.Fa ob .
Must be called before accessing
.Fa ob
for other purposes.
.It Ft void Fn atf_object_copy "atf_object_t *dest" "const atf_object_t *src"
Performs a deep copy of the object
.Fa src
into
.Fa dest .
Must be used whenever implementing deep copies for any other data type and,
in those cases, must be called before accessing
.Fa dest .
.It Ft void Fn atf_object_fini "atf_object_t *ob"
Finalizes the object pointed to by
.Fa ob .
Must be called as the very last step during the disposal of
.Fa ob .
.El
.\"
.Ss Free functions
.\"
.Bl -ohang
.It Ft void Fn atf_init_objects "void"
Initializes the
.Xr atf-c 3
object system.
Must be called at the very beginning of the process and before using any
data type provided by the library, and the call must happen only once.
The call to this function initializes global data structures used to manage
objects and installs exit checks to perform sanity-checking operations.
.It Ft void Fn atf_disable_exit_checks "void"
Disables the exit checks installed by
.Fn atf_init_objects .
Useful when preparing to run untrusted code (e.g. code that can exit at
any point without explicit cleanup of resources).
.El
.\"
.Sh SEE ALSO
.\"
.Xr atf-c 3 ,
.Xr atf 7
