# BEGIN `FreeBSD.subr`.
#
# Copyright (c) 2026 Enji Cooper <ngie@FreeBSD.org>.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause

atf_require_kmod_supported()
{
    true
}

# \brief FreeBSD specific helper routine for ensuring that a kmod has been
# loaded.
#
# \param kmod a target kmod.
atf_require_kmod()
{
    kldstat -q -m "${1}" || \
        atf_skip "The required kmod ${1} is not loaded"
}
# END `FreeBSD.subr`.
